### ISSUE TITLE
Be aware of when the html_search_url already contains a ?

### ISSUE THREAD

**Issue by johlym** [papertrail/papertrail-services#90]
As it stands, today, the html_search_url may contain a `?` and since we hard code a `?` into the string (https://github.com/papertrail/papertrail-services/blob/master/services/mail.rb#L48), the cited center ID isn't considered, as it should be.

**Comment by jplehmann** [comment]
in plain terms, "Link from email into log is broken if already contains ?"

**Comment by johlym** [comment]
Thanks. :)

**Comment by snorecone** [comment]
The fix for this is now live - feel free to re-open this issue if you find that it's not working. Cheers.
